### ISSUE TITLE
Missing parm when Parser::fromFile() calls Parser::fromDocument()

### ISSUE THREAD

**Issue by jlayt** [concrete5/doctrine-xml#4]
I'm using doctrine-xml 1.0 via Composer. In Parser::fromFile() on line 42 the call to fromDocument crashes as it doesn't pass through the $platform parameter:
`    return static::fromDocument($xml, $checkXml, $normalizeXml, $tableFilter);`
versus 
`    public static function fromDocument($xml, AbstractPlatform $platform, $checkXml = true, 
$normalizeXml = false, $tableFilter = null)`

**Comment by mlocati** [comment]
Fixed in https://github.com/concrete5/doctrine-xml/commit/11f32dc982352930f990bc28bca466564ff49537

I added release 1.0.1 that includes this fix.

Thanks!

**Comment by aembler** [comment]
Nice job, Michele

**Comment by mlocati** [comment]
> Nice job, Michele

It would have been an even nicer job if https://github.com/concrete5/doctrine-xml/commit/0c788071de33c90da2490c2f2373b5cc59d4a095 didn't introduce this bug :wink:
